name: Update Changelog on Merge

on:
  push:
    branches:
      - main # Only run when changes are pushed to main branch
  pull_request:
    types: [closed]
    branches:
      - dev

# Permissions needed to push the changelog commit and tags
permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    name: Update Changelog
    # Only run on merged PRs or direct pushes to main
    if: github.repository == 'darcher-/nodeVersionRange' && (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for standard-version to analyze all commit history for versioning

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc" # Using the updated .nvmrc file
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Verify standard-version is installed
        id: check_deps
        run: |
          if ! npm list -g standard-version &>/dev/null && ! npm list standard-version &>/dev/null; then
            echo "::set-output name=missing_deps::true"
            echo "standard-version is not installed"
          else
            echo "::set-output name=missing_deps::false"
            echo "standard-version is installed"
          fi

      - name: Install missing dependencies
        if: steps.check_deps.outputs.missing_deps == 'true'
        run: |
          npm install --save-dev standard-version
          echo "Added standard-version to devDependencies"

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run changelog generation and version bump
        id: changelog
        run: |
          npm run release || (echo "::set-output name=failed::true" && exit 1)
          echo "::set-output name=failed::false"

      - name: Commit package.json changes if needed
        if: steps.changelog.outputs.failed == 'true'
        run: |
          git add package.json package-lock.json
          git diff --staged --quiet || git commit -m "Update dependencies for changelog generation"
          git push

      - name: Retry changelog generation
        if: steps.changelog.outputs.failed == 'true'
        run: npm run release

      - name: Push changelog changes and tags
        run: git push --follow-tags origin main

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: v$(node -p "require('./package.json').version")
          name: Release v$(node -p "require('./package.json').version")
          body_path: CHANGELOG.md