name: Update Changelog on Merge

on:
  pull_request:
    branches:
      - main

# Permissions needed to push the changelog commit and tags
permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    name: Update Changelog
    # Only run on merged PRs or direct pushes to main
    if: github.repository == 'darcher-/nodeVersionRange' && (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for standard-version to analyze all commit history for versioning
          token: ${{ secrets.WORKFLOW_TOKEN }} # Use a PAT with proper permissions

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc" # Using the updated .nvmrc file
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Verify standard-version is installed
        id: check_deps
        run: |
          if ! npm list -g standard-version &>/dev/null && ! npm list standard-version &>/dev/null; then
            echo "::output name=missing_deps::true"
            echo "standard-version is not installed"
          else
            echo "::output name=missing_deps::false"
            echo "standard-version is installed"
          fi

      - name: Install missing dependencies
        if: steps.check_deps.outputs.missing_deps == 'true'
        run: |
          npm install --save-dev standard-version
          echo "Added standard-version to devDependencies"

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Verify Permissions
        id: verify_permissions
        run: |
          # Install GitHub CLI if not already available
          if ! command -v gh &> /dev/null; then
            echo "Installing GitHub CLI..."
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh
          fi

          # Check if token has workflows permission
          echo "Checking for workflows permission..."
          if gh api /installation/repositories &>/dev/null; then
            echo "::output name=has_workflows_permission::true"
            echo "Token has sufficient permissions"
          else
            echo "::output name=has_workflows_permission::false"
            echo "Token may lack workflows permission - will exclude workflow files"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Run changelog generation and version bump
        id: changelog
        run: |
          npm run release || (echo "::output name=failed::true" && exit 1)
          echo "::output name=failed::false"

      - name: Exclude workflow files if needed
        if: steps.verify_permissions.outputs.has_workflows_permission != 'true'
        run: |
          echo "Excluding workflow files from commit due to permission restrictions"
          git reset HEAD .github/workflows/

      - name: Commit package.json changes if needed
        if: steps.changelog.outputs.failed == 'true'
        run: |
          git add package.json package-lock.json
          git diff --staged --quiet || git commit -m "Update dependencies for changelog generation"
          git push

      - name: Retry changelog generation
        if: steps.changelog.outputs.failed == 'true'
        run: npm run release

      - name: Push changelog changes and tags
        run: |
          # Exclude workflow files if we don't have permission
          if [[ "${{ steps.verify_permissions.outputs.has_workflows_permission }}" != "true" ]]; then
            echo "Excluding workflow files from push due to permission restrictions"
            git reset HEAD .github/workflows/
          fi

          # Use a PAT with proper permissions
          git remote set-url origin https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push --follow-tags origin main
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: v$(node -p "require('./package.json').version")
          name: Release v$(node -p "require('./package.json').version")
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}