name: Update Changelog on Merge

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

# Permissions needed to push the changelog commit and tags
permissions:
  contents: write

jobs:
  update-changelog:
    name: Update Changelog
    # Ensure this only runs on the specified repository, not on forks
    if: github.repository == 'idx.google.com/nodeversionrange-54636892'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for standard-version to analyze all commit history for versioning
          token: ${{ secrets.GITHUB_TOKEN }} # Or a PAT if GITHUB_TOKEN lacks permission for protected main or tag creation

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc" # Or specify directly: node-version: '20'
          cache: "npm"

      - name: Install dependencies
        run: npm ci # Ensure standard-version (or similar) is a devDependency

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run changelog generation and version bump
        run: |
          # This command assumes 'standard-version' is used and configured.
          # It will typically:
          # 1. Determine the new version based on commit messages.
          # 2. Update package.json and package-lock.json with the new version.
          # 3. Generate/update CHANGELOG.md.
          # 4. Create a commit with these changes.
          # 5. Create a git tag for the new version.
          npm run release # Or: npx standard-version
        # env:
        # If your 'main' branch is protected and requires a PAT to push or create tags:
        # GITHUB_TOKEN: ${{ secrets.YOUR_PAT_WITH_REPO_SCOPE }}
        # By default, the GITHUB_TOKEN provided to the action might have sufficient rights
        # if your branch protection rules aren't too strict.

      - name: Push changelog changes and tags
        run: git push --follow-tags origin main
        # env:
        # Same as above, if a PAT is needed for pushing to a protected main branch.
        # GITHUB_TOKEN: ${{ secrets.YOUR_PAT_WITH_REPO_SCOPE }}
