name: Node.js CI

on:
  pull_request:
    branches: [ main ] # Adjust if your main branch has a different name, e.g., master

jobs:
  test:
    name: Test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # We test on Node 16.x, 18.x, and 20.x as the `node --test` runner
        # is well-supported in these versions.
        # Your `engines.node` is ">=14.17.0", but `node --test` CLI
        # became stable in later versions (16.17.0+/18.0.0+).

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Cache npm dependencies

      - name: Install dependencies
        run: npm ci # Use ci for cleaner, faster, and more reliable installs

      - name: Run tests
        run: npm test