name: Node.js CI

on:
  pull_request:
    branches: [ main ] # Adjust if your main branch has a different name, e.g., master

permissions:
  contents: write # Required to commit README.md changes
  pull-requests: read # Standard permission

jobs:
  test:
    name: Test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # We test on Node 16.x, 18.x, and 20.x as the `node --test` runner
        # is well-supported in these versions.
        # Your `engines.node` is ">=14.17.0", but `node --test` CLI
        # became stable in later versions (16.17.0+/18.0.0+).

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Cache npm dependencies

      - name: Install dependencies
        run: npm ci # Use ci for cleaner, faster, and more reliable installs

      - name: Run tests and coverage
        run: npm run test:coverage

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-node-${{ matrix.node-version }}
          path: coverage/lcov-report/ # Default c8 HTML output
          if-no-files-found: warn

      - name: Update Coverage Badge in README
        if: matrix.node-version == '20.x' # Run only on one Node version to avoid conflicts
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GITHUB_TOKEN }} # Token to commit to the PR branch (works for same-repo PRs)
          commit_message: 'chore: Update coverage badge [skip ci]'
          branch: ${{ github.head_ref || github.ref_name }} # Commit to the PR branch or current branch if not a PR
          filename: README.md # File to update
          badge_name: 'coverage' # For <!-- coverage_start --> and <!-- coverage_end --> placeholders
          label: 'Coverage'
          message_path: 'coverage/coverage-summary.json:$.total.lines.pct' # Path to value and JSONPath
          val_suffix: '%' # Add % suffix to the coverage percentage
          # Default colors based on percentage: green >= 90, orange >= 70, red < 70