name: Documentation Index Generator

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Generate documentation
        run: |
          # Your documentation generation script
          echo "Generating documentation..."

      - name: Create a new branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          BRANCH_NAME="update-docs-$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "Update documentation"
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: $BRANCH_NAME
          title: "Update Documentation"
          body: "This PR updates the documentation index."

      - name: Create docs index
        run: |
          echo "# 📚 Project Documentation Index" > docs.md
          echo "" >> docs.md
          echo "## Core Documentation" >> docs.md
          echo "" >> docs.md

          # Add links to main documentation files
          if [ -f ".github/CHANGELOG.md" ]; then
            echo "- [Changelog](.github/CHANGELOG.md) - History of all notable changes" >> docs.md
          fi
          if [ -f ".github/CONTRIBUTING.md" ]; then
            echo "- [Contributing Guide](.github/CONTRIBUTING.md) - How to contribute to this project" >> docs.md
          fi
          if [ -f ".github/CODE_OF_CONDUCT.md" ]; then
            echo "- [Code of Conduct](.github/CODE_OF_CONDUCT.md) - Community guidelines" >> docs.md
          fi
          if [ -f ".github/SECURITY.md" ]; then
            echo "- [Security Policy](.github/SECURITY.md) - How to report security vulnerabilities" >> docs.md
          fi
          if [ -f ".github/LICENSE.md" ]; then
            echo "- [License](.github/LICENSE.md) - Project license information" >> docs.md
          fi
          if [ -f ".github/CITATION.md" ]; then
            echo "- [Citation Information](.github/CITATION.md) - How to cite this project" >> docs.md
          fi
          if [ -f ".github/CODEOWNERS.md" ]; then
            echo "- [Code Owners](.github/CODEOWNERS.md) - Maintainers and reviewers" >> docs.md
          fi

          # Add links to other markdown files
          echo "" >> docs.md
          echo "## Additional Documentation" >> docs.md
          echo "" >> docs.md

          find . -name "*.md" ! -name "docs.md" ! -path "./.github/*" ! -path "./README.md" | sort | while read file; do
            filepath=$(echo "$file" | sed 's|^./||')
            title=$(head -n 1 "$file" | sed 's/^#\s*//' | sed 's/^<!-- filepath:.* -->//')
            if [ -z "$title" ]; then
              title=$(basename "$file" .md | sed 's/_/ /g' | sed 's/\b\(.\)/\u\1/g')
            fi
            echo "- [$title]($filepath)" >> docs.md
          done

          # Add README separately with proper formatting
          if [ -f "README.md" ]; then
            echo "- [README](README.md) - Project overview and getting started guide" >> docs.md
          fi

          echo "" >> docs.md
          echo "## Node.js Version Compatibility" >> docs.md
          echo "" >> docs.md
          echo "This project provides tools to analyze Node.js version compatibility across your project dependencies." >> docs.md
          echo "For more detailed information, please refer to the documentation files above." >> docs.md
          echo "" >> docs.md
          echo "---" >> docs.md
          echo "" >> docs.md
          echo "*This index is automatically generated and updated by GitHub Actions.*" >> docs.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "docs: update documentation index"
          add: "docs.md"
