# Suggested code may be subject to a license. Learn more: ~LicenseLog:2664196719.
name: Code Formatting on Merge

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install Prettier
        run: npm install --global prettier
      - name: Format files
        run: prettier --write "**/*.{js,css,html,yml,json,md}"
      - name: Commit changes
        uses: stefanprodan/commit-changes@v2
        with:
          commit_message: Format code with Prettier
          github_token: ${{ secrets.GITHUB_TOKEN }}
