name: Labeler

on:
  pull_request_target:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Apply project labels
      uses: actions/labeler@v5
      with:
        dot: true
        sync-labels: true
        configuration-path: .github/labeler.yml
        repo-token: "${{ secrets.GITHUB_TOKEN }}"