# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '28 19 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale due to inactivity. If you believe this is in error or wish to keep it open, please add a comment or update the issue. For more information, see our contributing guidelines: https://github.com/your-repo/contributing'
        stale-pr-message: 'This pull request has been marked as stale due to inactivity. If you would like to keep it open, please update it or leave a comment to let us know. Otherwise, it will be closed soon.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
