name: Mark stale issues and PRs

on:
  schedule:
  - cron: '28 19 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale due to inactivity. Please add a comment or update the issue to keep it open.'
        stale-pr-message: 'This pull request has been marked as stale due to inactivity. Please update it or leave a comment to keep it open.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 60
        days-before-close: 7
