name: Inactive Issues Monitor

on:
  schedule:
    - cron: "39 5 * * 1" # Run weekly on Mondays at 5:39 AM

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "⚠️ This issue has been inactive for 60 days and is marked as stale. Please add a comment or update the issue within 7 days to keep it open, otherwise it will be automatically closed."
          stale-pr-message: "⚠️ This pull request has been inactive for 60 days and is marked as stale. Please update it or leave a comment within 7 days to keep it open, otherwise it will be automatically closed."
          stale-issue-label: "inactive-issue"
          stale-pr-label: "inactive-pr"
          days-before-stale: 60
          days-before-close: 7
